services:
  app:
    image: ghcr.io/bolin8017/telegram-message-migrator:latest
    pull_policy: always
    build: .
    ports:
      - "${PORT:-8000}:8000"
    env_file:
      - .env
    volumes:
      - app_data:/data
    restart: unless-stopped

volumes:
  app_data:
